remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Make Ten! Support
description: Support page for the Make Ten! iOS puzzle game
show_downloads: false

github:
  is_project_page: false
